# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/surya/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),surya)

$(call add-radio-file-sha1-checked,radio/BTFM.bin,)
$(call add-radio-file-sha1-checked,radio/NON-HLOS.bin,)
$(call add-radio-file-sha1-checked,radio/abl.elf,dbbc32e89ca68a60436c3e854405a8b1efeb8fcf)
$(call add-radio-file-sha1-checked,radio/aop.mbn,a882a33ee29f3ab2bc31e7acb79097b887fcef1b)
$(call add-radio-file-sha1-checked,radio/cmnlib.mbn,5529386716c6202fd22499c1f2501fef393c9876)
$(call add-radio-file-sha1-checked,radio/cmnlib64.mbn,1cfa661df1bd4c5553a897d5efcc1e5c576473ce)
$(call add-radio-file-sha1-checked,radio/devcfg.mbn,d7c307c8806ac25d255a955f7735e1ff6c7e3c0e)
$(call add-radio-file-sha1-checked,radio/dspso.bin,)
$(call add-radio-file-sha1-checked,radio/ffu.img,f1e5f71fa958f200a58e4a33047855da3730a34f)
$(call add-radio-file-sha1-checked,radio/hyp.mbn,d09950017f0c2b742632e77e7299dbfb49ae90de)
$(call add-radio-file-sha1-checked,radio/imagefv.elf,94f4994f6fafa28b1cd0dbde03d9187598d8fdd6)
$(call add-radio-file-sha1-checked,radio/km4.mbn,)
$(call add-radio-file-sha1-checked,radio/qupv3fw.elf,)
$(call add-radio-file-sha1-checked,radio/storsec.mbn,50c976ea8529037508a3d82c854ed52cee8edbcd)
$(call add-radio-file-sha1-checked,radio/tz.mbn,430fdf5932313c3950c21f1e1ebe9999aa2e4486)
$(call add-radio-file-sha1-checked,radio/uefi_sec.mbn,)
$(call add-radio-file-sha1-checked,radio/xbl.elf,a9fef573654bab498a953b9d8f8b7e7bdeef0f0a)
$(call add-radio-file-sha1-checked,radio/xbl_config.elf,db11157c3ffb64b7b3b1752b4d3683e42475a385)

endif
